language: python
python:
- '3.6'
install:
env:
  secure: q9kX1t8V97MAQfatZnO7ndC5CV4HXJV29AWP0SaJYc7Pfhwp2V0RIkVenoMd7p1y3BW9JA/lf8tY06thvaeJwZf0xSIHj87RpqPmCFE11UUoTP4/doCc9Cr5b2NEBT5kdQNaUNBXoXjUs2TKsoFNquJ/mahZgQhottnpvJibX8h0UJwIqBdCyC6GYSPA2IAB2WZghIFBYl65+iEopb06HeUyg7uMS/VOdnBm0791b7vgFNhBzPzJT/++ar9L4dHecmECDRUD9IEQA5uh8XXtA4RZGp4rJSVm+3VwrxeDimr9nvMG9RBtVmc0/c6RXEVbJOYGLtDD90/A6P0L+/5Ijmzg8UAPrlol25mm0VIMfpSrlM0P7B/ov7r52I0sNej4YbcSQdoPzplsNRYV/GlDR8jNsBQvUwhUm6PWVrczD+LxGAc88/9En1iYYw/zHL6OXZaUEYb2aW5kjKQ9OvZGK5aov1z1sp3LOBtxmrjM4ERjS20yBmHm1MgQhUh7ECwBUSwddjNMrrv2wMROgJKSKxTj7l/pXWiaALkhaU78JkPacIW6S3o5GkymANQD/jpNkIocW/4+7XDIxW7VJzxISyYpRJ7eLoyeGjogd7p8Znz6hLZsoUgE7uy7C+3Bh0k3XsM/QPlllmCA41vU3V9R0/6eV/tBLIhnSsv6XyuastQ=
script: "./unittests"
deploy:
- provider: lambda
  function_name: githubInfo
  region: us-east-1
  role: arn:aws:iam::980316180835:role/lambda_techem_skill
  runtime: python3.6
  module_name: alexa_py
  handler_name: lambda_handler
  zip: "./src"
  access_key_id: AKIAJC4OTPBSMBJD4ZBA
  on:
    branch: master
  secret_access_key:
    secure: Cvvwzr3J0IaeN3LoMLSDZH9mwHOyPqWouw6dLe7CjM5sFXbl7NAX82Gh2IedCRge3Rlj2hNd/jBF89qN6D2SVoFBQgtFwdIV4xdYiAkLV8xB/zm4i95FnKd67kxs6z3Fv/eUgt4x33Vj9NeLHoyjqVE0FAPOMfFbfkuP1cY3u+LPTjPjwntPScYX2L3xQlpnYp+eCQazwpIRMJGoHojgD6tTGH+KbCBIOQ6ifO0BEurM5Att5yzipMjHx0oGkaspgAnJ2GvNt4tb9PD5RWjFBDp3vAI+Z2TG/aTKpxivZWCtVfQFUplwK7bPSmA0d72VgfCVvtgZfAqOUHO/9LL5jvAEJ+0J9I0Tnq0LBEX+840m3oVshQVuas2GuZnuEVhdAZzPvTEr+q3th9RP0dXB3Ib19OSOQyka75Zk/VVazGoKBVoGMUr0JRfd+x4hVXjTjbF0fBHaPoYeaacb3yovoS8RTqTHAuNnUtTgTxXSqYKKpVwG4vqIpJG1oNHPCwIj08nro8Q5ZnhW/yiRpW980/akp4d45LwGbnyR1NGd/is9Bliq5OGC0l3Sa1OTVHWvpdgoUgqXU+4zQFXvzZ1Rb5YU5RRtjShWvs+1CX1Ow3MvSCsyQ3L2cUfnWM+4RTbpDplvH4F6icWvXN2qWFfDFSU2R1qekDpIhO5RsGUqnHU=
- provider: s3
  bucket: alexa-python-biz
  local-dir: responses
  skip_cleanup: true
  on:
    branch: master
  access_key_id: AKIAJC4OTPBSMBJD4ZBA
  secret_access_key:
    secure: Cvvwzr3J0IaeN3LoMLSDZH9mwHOyPqWouw6dLe7CjM5sFXbl7NAX82Gh2IedCRge3Rlj2hNd/jBF89qN6D2SVoFBQgtFwdIV4xdYiAkLV8xB/zm4i95FnKd67kxs6z3Fv/eUgt4x33Vj9NeLHoyjqVE0FAPOMfFbfkuP1cY3u+LPTjPjwntPScYX2L3xQlpnYp+eCQazwpIRMJGoHojgD6tTGH+KbCBIOQ6ifO0BEurM5Att5yzipMjHx0oGkaspgAnJ2GvNt4tb9PD5RWjFBDp3vAI+Z2TG/aTKpxivZWCtVfQFUplwK7bPSmA0d72VgfCVvtgZfAqOUHO/9LL5jvAEJ+0J9I0Tnq0LBEX+840m3oVshQVuas2GuZnuEVhdAZzPvTEr+q3th9RP0dXB3Ib19OSOQyka75Zk/VVazGoKBVoGMUr0JRfd+x4hVXjTjbF0fBHaPoYeaacb3yovoS8RTqTHAuNnUtTgTxXSqYKKpVwG4vqIpJG1oNHPCwIj08nro8Q5ZnhW/yiRpW980/akp4d45LwGbnyR1NGd/is9Bliq5OGC0l3Sa1OTVHWvpdgoUgqXU+4zQFXvzZ1Rb5YU5RRtjShWvs+1CX1Ow3MvSCsyQ3L2cUfnWM+4RTbpDplvH4F6icWvXN2qWFfDFSU2R1qekDpIhO5RsGUqnHU=
