language: python
python:
- '3.6'
install:
env:
  secure: <update>
script: "./build"
deploy:
- provider: lambda
  function_name: <update>
  region: us-east-1
  role: <update>
  runtime: python3.6
  module_name: alexa_py
  handler_name: lambda_handler
  zip: "./src"
  access_key_id: <update>
  on:
    branch: master
  secret_access_key:
    secure: <update>
- provider: s3
  bucket: alexa-responses
  local-dir: responses
  skip_cleanup: true
  on:
    branch: master
  access_key_id: <update - same as above>
  secret_access_key:
    secure: <update - same as above>
